[workspace]
members = [
    "acceptance",
    "derive-macros",
    "ffi",
    "kernel",
    "kernel/examples/*",
    "test-utils",
    "feature-tests",
    "uc-client", # WIP: this is an experimental UC client for catalog-managed table work
]
# note that in addition to the members above, the workspace includes examples:
# - inspect-table
# - read-table-changes
# - read-table-multi-threaded
# - read-table-single-threaded
# - write-table
resolver = "2"

[workspace.package]
edition = "2021"
homepage = "https://delta.io"
keywords = ["deltalake", "delta", "datalake"]
license = "Apache-2.0"
repository = "https://github.com/delta-io/delta-kernel-rs"
readme = "README.md"
rust-version = "1.84"
version = "0.16.0"

[patch.crates-io]
arrow = { git = "https://github.com/spiceai/arrow-rs.git", rev = "bfada495edbfc6ddcdabd3d2d93ac6e013552acd" }        # spiceai-56
arrow-arith = { git = "https://github.com/spiceai/arrow-rs.git", rev = "bfada495edbfc6ddcdabd3d2d93ac6e013552acd" }  # spiceai-56
arrow-array = { git = "https://github.com/spiceai/arrow-rs.git", rev = "bfada495edbfc6ddcdabd3d2d93ac6e013552acd" }  # spiceai-56
arrow-buffer = { git = "https://github.com/spiceai/arrow-rs.git", rev = "bfada495edbfc6ddcdabd3d2d93ac6e013552acd" } # spiceai-56
arrow-cast = { git = "https://github.com/spiceai/arrow-rs.git", rev = "bfada495edbfc6ddcdabd3d2d93ac6e013552acd" }   # spiceai-56
arrow-csv = { git = "https://github.com/spiceai/arrow-rs.git", rev = "bfada495edbfc6ddcdabd3d2d93ac6e013552acd" }    # spiceai-56
arrow-data = { git = "https://github.com/spiceai/arrow-rs.git", rev = "bfada495edbfc6ddcdabd3d2d93ac6e013552acd" }   # spiceai-56
arrow-flight = { git = "https://github.com/spiceai/arrow-rs.git", rev = "bfada495edbfc6ddcdabd3d2d93ac6e013552acd" } # spiceai-56
arrow-ipc = { git = "https://github.com/spiceai/arrow-rs.git", rev = "bfada495edbfc6ddcdabd3d2d93ac6e013552acd" }    # spiceai-56
arrow-json = { git = "https://github.com/spiceai/arrow-rs.git", rev = "bfada495edbfc6ddcdabd3d2d93ac6e013552acd" }   # spiceai-56
arrow-ord = { git = "https://github.com/spiceai/arrow-rs.git", rev = "bfada495edbfc6ddcdabd3d2d93ac6e013552acd" }    # spiceai-56
arrow-row = { git = "https://github.com/spiceai/arrow-rs.git", rev = "bfada495edbfc6ddcdabd3d2d93ac6e013552acd" }    # spiceai-56
arrow-schema = { git = "https://github.com/spiceai/arrow-rs.git", rev = "bfada495edbfc6ddcdabd3d2d93ac6e013552acd" } # spiceai-56
arrow-select = { git = "https://github.com/spiceai/arrow-rs.git", rev = "bfada495edbfc6ddcdabd3d2d93ac6e013552acd" } # spiceai-56
arrow-string = { git = "https://github.com/spiceai/arrow-rs.git", rev = "bfada495edbfc6ddcdabd3d2d93ac6e013552acd" } # spiceai-56
parquet = { git = "https://github.com/spiceai/arrow-rs.git", rev = "bfada495edbfc6ddcdabd3d2d93ac6e013552acd" }      # spiceai-56

# Use same object_store ref as spiceai-56
object_store = { git = "https://github.com/apache/arrow-rs-object-store", rev = "f0a772cd49d2ebb1f19f487ccd93d705f48dc891" }
